name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup C++ environment
    - name: Set up C++ environment
      uses: actions/setup-cpp@v2

    # Cache Conan packages to speed up build
    - name: Cache Conan packages
      uses: actions/cache@v3
      with:
        path: ~/.conan/data
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan-

    # Install Conan dependencies
    - name: Install Conan dependencies
      run: conan install ${GITHUB_WORKSPACE} --build=missing

    # Configure CMake
    - name: Configure CMake
      # Note: We run `conan install` in the previous step which generates `conanbuildinfo.cmake` file
      # We need to include this file in our CMake configuration by passing `-DCMAKE_MODULE_PATH`
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE}

    # Build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Run tests
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
